# Generated by Django 2.0.7 on 2018-07-07 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0025_auto_20180707_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourney',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='touneywinner', to='players.Players'),
        ),
    ]
